//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT321_SARMS_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Active { get; set; }
        public int ClassID { get; set; }
        public int Type { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> StaffID { get; set; }
    
        public virtual AttendanceType AttendanceType { get; set; }
        public virtual LectureClass Class { get; set; }
        public virtual Student Student { get; set; }
    }
}
