//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT321_SARMS_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        public int LectureId { get; set; }
        public Nullable<int> Day { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<double> Length { get; set; }
        public string Classroom { get; set; }
        public string UnitCode { get; set; }
    }
}
